### ISSUE TITLE
SSL Certificate expired

### ISSUE THREAD

**Issue by Menkid** [popcorn-official/popcorn-site#2]
Operating System Version:
iOS 6.3

Safari is raising a security alert when I try to connect to https://popcorntime.sh
It tells the certificate expired on 2017-01-30 13:38:00 UTC
There are 3 fields with dates in the certificates, but only the first one is expired: "Règlements des certificats" in french.

**Comment by ChrisAlderson** [comment]
Should be fixed.

**Comment by Menkid** [comment]
Works fine !
<3
