### ISSUE TITLE
Brazlian strings broken

### ISSUE THREAD

**Issue by ivanhtp** [popcorn-official/popcorn-site#6]
The PT_Br version of the website is clearly translated by a poor translation tool.

Portuguese natives almost mostly face problems in translation due incorrect localization (such as brazilians seeing Portugal portuguese or portuguese people seeing brazilian portuguese strings), but it doesn't seem the case here. Both countries are affected.

I looked up in this repo to fix it myself but the locale folder only has "en" strings. I thinks the other languages wasn't uploaded or commited.

Please update the repo so we could help to fix the language on the website.

**Comment by tiagodenoronha** [comment]
Yes please, looking to give a hand in translating for the PT_PT version!

**Comment by Cabritone** [comment]
I'm available to help in PT_PT Translation as well

**Comment by team-pct** [comment]
Hello guys 
Thank you for your interest 
you can help us here https://www.transifex.com/popcorn-time/popcorn-time-app/
